# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Little notes of life!
email: theanh.huy@gmail.com
description: >
  Hi, I'm a developer.
logo: https://avatars3.githubusercontent.com/u/975635?s=460&v=4
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theanh.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: The Anh Nguyen
bio: >
  I'm a developer. I have been working on the industry since 2011.
  I have been working in PHP and Javascript, both of them being my specialty.
  I'm interesting in using technology in solving real World issues, such as issues in agriculture, or issues in transportation.
author_image: https://avatars3.githubusercontent.com/u/975635?s=460&v=4
twitter_username: theanhhuy
github_username:  theanh

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
